# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "ubuntu/bionic64"
  config.vm.provider "virtualbox" do |v|
  # config.vm.network "public_network"
  v.customize ["modifyvm", :id, "--memory", 1024]
  end

  config.vm.define "wg-vm" do |wg-vm|
    wg-vm.vm.hostname = 'wg-vm'
  end
end
